import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Add build version and timestamp
const versionInfo = {
  version: "1.0.0",
  gitHash: process.env.NEXT_PUBLIC_GIT_SHA?.slice(0, 7) || "dev",
  buildTime: new Date().toISOString().split("T")[0],
};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <div className="w-full text-center py-2 px-4 bg-gray-100 dark:bg-gray-800 border-b border-gray-200 dark:border-gray-700">
          <p className="text-xs text-gray-500 dark:text-gray-400">
            Version {versionInfo.version} • Git Hash: {versionInfo.gitHash} • Built: {versionInfo.buildTime}
          </p>
        </div>
        <div className="flex-1">{children}</div>
      </body>
    </html>
  );
}
